openapi: 3.0.1
info:
  title: 'Code Help Admin'
  version: 1.0.0

servers:
  - url: http://localhost:4000/api/v1
    description: Open API specification

paths:
  /categories:
    get:
      tags: [ category ]
      operationId: getAllCategories
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryResponse'
    post:
      tags: [ category ]
      operationId: createCategory
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        203:
          description: Created.
  /categories/{name}:
    put:
      tags: [ category ]
      operationId: updateCategory
      parameters:
        - $ref: '#/components/parameters/CategoryName'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        204:
          description: No content.
        404:
          description: Not found.
        400:
          description: Bad request.
  /problems:
    get:
      tags: [ problem ]
      operationId: getAllProblems
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemResponse'
    post:
      tags: [ problem ]
      operationId: createProblem
      parameters:
        - in: query
          name: contestId
          required: false
          schema:
            type: integer
            example: 2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProblemRequest'
      description: Create a problem in the backend
      responses:
        201:
          description: Created

  /problems/{id}:
    get:
      tags: [ problem ]
      operationId: getProblem
      parameters:
        - $ref: '#/components/parameters/ProblemId'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        404:
          description: Not Found
        500:
          description: Internal server error
    put:
      tags: [ problem ]
      operationId: updateProblem
      parameters:
        - $ref: '#/components/parameters/ProblemId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProblemRequest'
      responses:
        200:
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
    delete:
      tags: [ problem ]
      operationId: deleteProblem
      parameters:
        - $ref: '#/components/parameters/ProblemId'
      responses:
        204:
          description: No Content
  /contests:
    get:
      tags: [ contest ]
      operationId: getAllContests
      responses:
        200:
          description: OK. All contests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContestResponse'
    post:
      tags: [ contest ]
      operationId: createContest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContestRequest'
      responses:
        203:
          description: No content
  /contests/{id}:
    get:
      tags: [ contest ]
      operationId: getContest
      parameters:
        - $ref: '#/components/parameters/ContestId'
      responses:
        200:
          description: OK. Contest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContestDetail'
    put:
      tags: [ contest ]
      operationId: updateContest
      parameters:
        - $ref: '#/components/parameters/ContestId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContestEditRequest'
      responses:
        200:
          description: No content
    delete:
      tags: [ contest ]
      operationId: deleteContest
      parameters:
        - $ref: '#/components/parameters/ContestId'
      responses:
        204:
          description: No content
components:
  parameters:
    CategoryName:
      in: path
      name: name
      required: true
      schema:
        type: string
    ProblemId:
      in: path
      name: id
      required: true
      schema:
        type: integer
        format: int64
    ContestId:
      in: path
      name: id
      required: true
      schema:
        type: integer
        format: int64
  schemas:
    ProblemResponse:
      type: object
      required: [ problems ]
      properties:
        problems:
          type: array
          items:
            $ref: '#/components/schemas/Problem'
    Problem:
      type: object
      required: [ id, title, difficulty ]
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        difficulty:
          $ref: '#/components/schemas/Difficulty'
        category:
          $ref: '#/components/schemas/Category'
    ProblemDetail:
      allOf:
        - $ref: '#/components/schemas/Problem'
        - type: object
          required: [ markdown, starterCode, runnerCode, testCases ]
          properties:
            markdown:
              type: string
              example: '## Two Sum... problem description'
            starterCode:
              $ref: '#/components/schemas/Code'
            runnerCode:
              $ref: '#/components/schemas/Code'
            testCases:
              $ref: '#/components/schemas/TestCases'
    TestCase:
      type: string
      example: |
        ABCD FIND GO
        CCBD FIND GO
    Code:
      type: string
      example: |
        function (arg1) {
          // code goes here
        }
    ProblemRequest:
      type: object
      required: [ title, difficulty, markdown, starterCode, runnerCode, testCases ]
      properties:
        category:
          $ref: '#/components/schemas/Category'
        title:
          type: string
          example: 'Two sum'
        difficulty:
          $ref: '#/components/schemas/Difficulty'
        markdown:
          type: string
          example: '## Two Sum... problem description'
        starterCode:
          $ref: "#/components/schemas/Code"
        runnerCode:
          $ref: "#/components/schemas/Code"
        testCases:
          $ref: '#/components/schemas/TestCases'
    ContestResponse:
      type: object
      required: [ contests ]
      properties:
        contests:
          type: array
          items:
            $ref: '#/components/schemas/Contest'
    ContestRequest:
      type: object
      required: [ name, duration, startsOn ]
      properties:
        name:
          type: string
          example: 'Contest name'
        status:
          $ref: '#/components/schemas/ContestStatus'
        duration:
          type: string
          format: duration
          example: 1h30m
        startsOn:
          $ref: '#/components/schemas/Date'
    ContestEditRequest:
      allOf:
        - $ref: '#/components/schemas/ContestRequest'
        - type: object
          properties:
            problems:
              type: array
              items:
                type: object
                properties:
                  contestProblemId:
                    type: integer
                    format: int64
                  score:
                    type: integer
    Contest:
      type: object
      required: [ id, name, status, duration, startsOn ]
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: 'Contest name'
        status:
          $ref: '#/components/schemas/ContestStatus'
        duration:
          type: string
          format: duration
          example: 1h30m
        startsOn:
          $ref: '#/components/schemas/Date'
    ContestDetail:
      allOf:
        - $ref: '#/components/schemas/Contest'
        - type: object
          required: [ problems ]
          properties:
            problems:
              type: array
              items:
                $ref: '#/components/schemas/ContestProblem'
    ContestProblem:
      allOf:
        - $ref: '#/components/schemas/Problem'
        - type: object
          required: [ contestProblemId, score ]
          properties:
            contestProblemId:
              type: integer
              format: int64
            score:
              type: integer
    CategoryResponse:
      type: object
      required: [ categories ]
      properties:
        categories:
          type: array
          items:
            $ref: '#/components/schemas/Category'
    Category:
      type: object
      required: [ name ]
      properties:
        name:
          type: string
          example: 'Binary trees'

    ContestStatus:
      type: string
      enum: [ OPEN, STARTED, CLOSED ]
    Difficulty:
      type: string
      enum: [ EASY, MEDIUM, HARD ]
      example: 'EASY'

    File:
      type: string
      format: binary
    Date:
      type: string
      format: date
      example: '2022-05-16'
    TestCases:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            format: int64
          in:
            $ref: '#/components/schemas/TestCase'
          out:
            $ref: '#/components/schemas/TestCase'