version: '3'
services:
  code-help-ingress:
    image: code-help-ingress
    container_name: code-help-ingress
    build: .
    volumes:
      - ./nginx.conf/:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 433:433
    depends_on:
      - code-help-keycloak-iam

  code-help-keycloak-iam:
    image: keycloak/keycloak:21.0
    container_name: code-help-keycloak-iam
    ports:
      - 8443:8443
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
      - --import-realm
      - --http-relative-path=/iam
      - --proxy=edge
      - --hostname-url=http://localhost/iam
      - --hostname-admin-url=http://localhost/iam
    volumes:
      - ./code-help-keycloak-iam/realms:/opt/keycloak/data/import
  # code-help-admin-ui:
  #   container_name: code-help-admin-ui
  #   build: code-help-admin-ui
  #   environment:
  #    - VITE_ADMIN_API_URL=http://localhost:3000/api
  #    - VITE_KEYCLOAK_URL=http://localhost
  #    - VITE_KEYCLOAK_REALM=code-help
  #    - VITE_KEYCLOAK_CLIENTID=code-help-client
  #   ports:
  #     - 5432:5432

volumes:
  code-help-forum-postgres-data:
  code-help-core-neo4j-data:
  code-help-core-neo4j-logs:
  code-help-core-neo4j-plugins: