FROM node:16-alpine as builder

WORKDIR /admin-ui

COPY ./code-help-admin-ui .

ARG VITE_ADMIN_API_URL
ENV VITE_ADMIN_API_URL=$VITE_ADMIN_API_URL
ARG VITE_KEYCLOAK_URL
ENV VITE_KEYCLOAK_URL=$VITE_KEYCLOAK_URL
ARG VITE_KEYCLOAK_REALM
ENV VITE_KEYCLOAK_REALM=$VITE_KEYCLOAK_REALM
ARG VITE_KEYCLOAK_CLIENTID
ENV VITE_KEYCLOAK_CLIENTID=$VITE_KEYCLOAK_CLIENTID
ARG VITE_BASE_ROUTE
ENV VITE_BASE_ROUTE=$VITE_BASE_ROUTE

RUN npm install
RUN npm run build

FROM nginx:stable as build

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /admin-ui/dist/ /usr/share/nginx/html/admin-ui/

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]