version: '3'
services:
  code-help-admin-backend:
    image: code-help-admin-backend
    container_name: code-help-admin-backend
    build:
      context: code-help-admin-backend
      dockerfile: ./@global/deploy/Dockerfile
    environment:
      - CORE_ADMIN_API_SERVER_URL=http://code-help-core:3000/api
      - OAUTH2_RESOURCESERVER_JWT_ISSUERURI=http://localhost/iam/realms/code-help
      - OAUTH2_RESOURCESERVER_JWT__DISCOVERYISSUERURI=http://code-help-keycloak-iam:8080/iam/realms/code-help
      - OAUTH2_RESOURCESERVER_JWT_JWKSETURI=http://code-help-keycloak-iam:8080/iam/realms/code-help/protocol/openid-connect/certs
    ports:
      - 4000:4000
    depends_on:
      - code-help-keycloak-iam

  code-help-ingress:
    image: code-help-ingress
    container_name: code-help-ingress
    build:
      context: .
      args:
        - VITE_ADMIN_API_URL=http://localhost/admin/api/v1
        - VITE_KEYCLOAK_URL=http://localhost/iam
        - VITE_KEYCLOAK_REALM=code-help
        - VITE_KEYCLOAK_CLIENTID=code-help-flutter
        - VITE_BASE_ROUTE=/admin-ui
    volumes:
      - ./nginx.conf/:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 433:433
    depends_on:
      - code-help-keycloak-iam
      - code-help-admin-backend

  code-help-keycloak-iam:
    image: keycloak/keycloak:21.0
    container_name: code-help-keycloak-iam
    ports:
      - 8443:8443
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
      - --import-realm
      - --http-relative-path=/iam
      - --proxy=edge
      - --hostname-url=http://localhost/iam
      - --hostname-admin-url=http://localhost/iam
    volumes:
      - ./code-help-keycloak-iam/realms:/opt/keycloak/data/import

volumes:
  code-help-forum-postgres-data:
  code-help-core-neo4j-data:
  code-help-core-neo4j-logs:
  code-help-core-neo4j-plugins: