/*
 * Coding helper spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package codehelp_core_api




type ContestEntry struct {

	Name string `json:"name"`

	Duration string `json:"duration"`

	StartsOn string `json:"startsOn"`

	Id int32 `json:"id,omitempty"`

	Status ContestStatus `json:"status,omitempty"`

	Problems []ContestProblem `json:"problems"`
}

// AssertContestEntryRequired checks if the required fields are not zero-ed
func AssertContestEntryRequired(obj ContestEntry) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"duration": obj.Duration,
		"startsOn": obj.StartsOn,
		"problems": obj.Problems,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Problems {
		if err := AssertContestProblemRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertContestEntryConstraints checks if the values respects the defined constraints
func AssertContestEntryConstraints(obj ContestEntry) error {
	return nil
}
