/*
 * Coding helper spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package codehelp_core_api




type RunCodeRequest struct {

	ProblemId int32 `json:"problemId,omitempty"`

	Language string `json:"language,omitempty"`

	Code string `json:"code,omitempty"`

	Input string `json:"input,omitempty"`
}

// AssertRunCodeRequestRequired checks if the required fields are not zero-ed
func AssertRunCodeRequestRequired(obj RunCodeRequest) error {
	return nil
}

// AssertRunCodeRequestConstraints checks if the values respects the defined constraints
func AssertRunCodeRequestConstraints(obj RunCodeRequest) error {
	return nil
}
