/*
 * Coding helper spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package codehelp_core_api




type ProblemsTop10Response struct {

	Problems []ProblemByLikes `json:"problems"`
}

// AssertProblemsTop10ResponseRequired checks if the required fields are not zero-ed
func AssertProblemsTop10ResponseRequired(obj ProblemsTop10Response) error {
	elements := map[string]interface{}{
		"problems": obj.Problems,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Problems {
		if err := AssertProblemByLikesRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertProblemsTop10ResponseConstraints checks if the values respects the defined constraints
func AssertProblemsTop10ResponseConstraints(obj ProblemsTop10Response) error {
	return nil
}
