/*
 * Coding helper spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package codehelp_core_api




type UserStatistics struct {

	Solved int32 `json:"solved"`

	Easy int32 `json:"easy"`

	Medium int32 `json:"medium"`

	Hard int32 `json:"hard"`
}

// AssertUserStatisticsRequired checks if the required fields are not zero-ed
func AssertUserStatisticsRequired(obj UserStatistics) error {
	elements := map[string]interface{}{
		"solved": obj.Solved,
		"easy": obj.Easy,
		"medium": obj.Medium,
		"hard": obj.Hard,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertUserStatisticsConstraints checks if the values respects the defined constraints
func AssertUserStatisticsConstraints(obj UserStatistics) error {
	return nil
}
