/*
 * Coding helper spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package codehelp_core_api




type ProblemsResponse struct {

	Problems []ProblemEntry `json:"problems"`
}

// AssertProblemsResponseRequired checks if the required fields are not zero-ed
func AssertProblemsResponseRequired(obj ProblemsResponse) error {
	elements := map[string]interface{}{
		"problems": obj.Problems,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Problems {
		if err := AssertProblemEntryRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertProblemsResponseConstraints checks if the values respects the defined constraints
func AssertProblemsResponseConstraints(obj ProblemsResponse) error {
	return nil
}
