/*
 * Coding helper spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package codehelp_core_api




type GetSubmissionsRequest struct {

	ProblemId int32 `json:"problemId,omitempty"`
}

// AssertGetSubmissionsRequestRequired checks if the required fields are not zero-ed
func AssertGetSubmissionsRequestRequired(obj GetSubmissionsRequest) error {
	return nil
}

// AssertGetSubmissionsRequestConstraints checks if the values respects the defined constraints
func AssertGetSubmissionsRequestConstraints(obj GetSubmissionsRequest) error {
	return nil
}
