/*
 * Coding helper spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package codehelp_core_api




type SubmissionsResponse struct {

	Submissions []SubmissionEntry `json:"submissions"`
}

// AssertSubmissionsResponseRequired checks if the required fields are not zero-ed
func AssertSubmissionsResponseRequired(obj SubmissionsResponse) error {
	elements := map[string]interface{}{
		"submissions": obj.Submissions,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Submissions {
		if err := AssertSubmissionEntryRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertSubmissionsResponseConstraints checks if the values respects the defined constraints
func AssertSubmissionsResponseConstraints(obj SubmissionsResponse) error {
	return nil
}
