/*
 * Coding helper spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package codehelp_core_api




type SetContestProblemScoreRequest struct {

	Score int32 `json:"score,omitempty"`
}

// AssertSetContestProblemScoreRequestRequired checks if the required fields are not zero-ed
func AssertSetContestProblemScoreRequestRequired(obj SetContestProblemScoreRequest) error {
	return nil
}

// AssertSetContestProblemScoreRequestConstraints checks if the values respects the defined constraints
func AssertSetContestProblemScoreRequestConstraints(obj SetContestProblemScoreRequest) error {
	return nil
}
