/*
 * Coding helper spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package codehelp_core_api




type CategoriesResponse struct {

	Categories []Category `json:"categories"`
}

// AssertCategoriesResponseRequired checks if the required fields are not zero-ed
func AssertCategoriesResponseRequired(obj CategoriesResponse) error {
	elements := map[string]interface{}{
		"categories": obj.Categories,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Categories {
		if err := AssertCategoryRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertCategoriesResponseConstraints checks if the values respects the defined constraints
func AssertCategoriesResponseConstraints(obj CategoriesResponse) error {
	return nil
}
