/*
 * Forum application
 *
 * Forum application api
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package code_help_forum_api




type Categories struct {

	Categories []Category `json:"categories"`
}

// AssertCategoriesRequired checks if the required fields are not zero-ed
func AssertCategoriesRequired(obj Categories) error {
	elements := map[string]interface{}{
		"categories": obj.Categories,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Categories {
		if err := AssertCategoryRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertCategoriesConstraints checks if the values respects the defined constraints
func AssertCategoriesConstraints(obj Categories) error {
	return nil
}
