/*
 * Forum application
 *
 * Forum application api
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package code_help_forum_api




type ShortCommunity struct {

	Name string `json:"name"`

	Description string `json:"description"`

	Image string `json:"image,omitempty"`

	Categories []Category `json:"categories,omitempty"`
}

// AssertShortCommunityRequired checks if the required fields are not zero-ed
func AssertShortCommunityRequired(obj ShortCommunity) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"description": obj.Description,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Categories {
		if err := AssertCategoryRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertShortCommunityConstraints checks if the values respects the defined constraints
func AssertShortCommunityConstraints(obj ShortCommunity) error {
	return nil
}
