/*
 * Forum application
 *
 * Forum application api
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package code_help_forum_api




type Posts struct {

	Posts []Post `json:"posts,omitempty"`
}

// AssertPostsRequired checks if the required fields are not zero-ed
func AssertPostsRequired(obj Posts) error {
	for _, el := range obj.Posts {
		if err := AssertPostRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertPostsConstraints checks if the values respects the defined constraints
func AssertPostsConstraints(obj Posts) error {
	return nil
}
