/*
 * Forum application
 *
 * Forum application api
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package code_help_forum_api


import (
	"time"
)



type ShortPost struct {

	Uid string `json:"uid"`

	Title string `json:"title"`

	Created time.Time `json:"created"`

	User User `json:"user"`
}

// AssertShortPostRequired checks if the required fields are not zero-ed
func AssertShortPostRequired(obj ShortPost) error {
	elements := map[string]interface{}{
		"uid": obj.Uid,
		"title": obj.Title,
		"created": obj.Created,
		"user": obj.User,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertUserRequired(obj.User); err != nil {
		return err
	}
	return nil
}

// AssertShortPostConstraints checks if the values respects the defined constraints
func AssertShortPostConstraints(obj ShortPost) error {
	return nil
}
