/*
 * Forum application
 *
 * Forum application api
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package code_help_forum_api




type Comments struct {

	Comments []Comment `json:"comments,omitempty"`
}

// AssertCommentsRequired checks if the required fields are not zero-ed
func AssertCommentsRequired(obj Comments) error {
	for _, el := range obj.Comments {
		if err := AssertCommentRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertCommentsConstraints checks if the values respects the defined constraints
func AssertCommentsConstraints(obj Comments) error {
	return nil
}
