/*
 * Forum application
 *
 * Forum application api
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package code_help_forum_api




type CommunityRequest struct {

	Name string `json:"name"`

	Description string `json:"description"`

	Image string `json:"image,omitempty"`

	Categories CommunityRequestCategories `json:"categories,omitempty"`
}

// AssertCommunityRequestRequired checks if the required fields are not zero-ed
func AssertCommunityRequestRequired(obj CommunityRequest) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"description": obj.Description,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertCommunityRequestCategoriesRequired(obj.Categories); err != nil {
		return err
	}
	return nil
}

// AssertCommunityRequestConstraints checks if the values respects the defined constraints
func AssertCommunityRequestConstraints(obj CommunityRequest) error {
	return nil
}
