/*
 * Forum application
 *
 * Forum application api
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package code_help_forum_api




type Users struct {

	Users []User `json:"users"`
}

// AssertUsersRequired checks if the required fields are not zero-ed
func AssertUsersRequired(obj Users) error {
	elements := map[string]interface{}{
		"users": obj.Users,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Users {
		if err := AssertUserRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertUsersConstraints checks if the values respects the defined constraints
func AssertUsersConstraints(obj Users) error {
	return nil
}
