/*
 * Forum application
 *
 * Forum application api
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package code_help_forum_api




type CategoryCreate struct {

	Name string `json:"name"`
}

// AssertCategoryCreateRequired checks if the required fields are not zero-ed
func AssertCategoryCreateRequired(obj CategoryCreate) error {
	elements := map[string]interface{}{
		"name": obj.Name,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCategoryCreateConstraints checks if the values respects the defined constraints
func AssertCategoryCreateConstraints(obj CategoryCreate) error {
	return nil
}
