/*
 * Forum application
 *
 * Forum application api
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package code_help_forum_api




type ShortPosts struct {

	Posts []ShortPost `json:"posts,omitempty"`
}

// AssertShortPostsRequired checks if the required fields are not zero-ed
func AssertShortPostsRequired(obj ShortPosts) error {
	for _, el := range obj.Posts {
		if err := AssertShortPostRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertShortPostsConstraints checks if the values respects the defined constraints
func AssertShortPostsConstraints(obj ShortPosts) error {
	return nil
}
