/*
 * Forum application
 *
 * Forum application api
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package code_help_forum_api




type PostRequest struct {

	Title string `json:"title"`

	Content string `json:"content"`
}

// AssertPostRequestRequired checks if the required fields are not zero-ed
func AssertPostRequestRequired(obj PostRequest) error {
	elements := map[string]interface{}{
		"title": obj.Title,
		"content": obj.Content,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertPostRequestConstraints checks if the values respects the defined constraints
func AssertPostRequestConstraints(obj PostRequest) error {
	return nil
}
